### ISSUE TITLE
How tu build an run

### ISSUE THREAD

**Issue by Ralffan** [KChadwick96/rFactor2-Overlay-v2#8]
Hi Kieran and thank you for this overlay, it looks very good. I'm not sure about how to correctly build an run the project (I never worked with react nor Node.js). I ran the command "yarn", and then built with command "npm run build", both commands seemed to run ok, and a build folder was generated. However, I can't see what I expected in localhost:5000 after running "serve -s" in the build folder, instead I see something about Storybook and "No knobs found", whetere the game is running or not.

Can you provide help to build and run correctly the application?

A part from that, I'm also interested to know where did you find information about the new API from rFactor 2, do you have any documentation?

Thanks.

**Comment by KChadwick96** [comment]
Hey sorry for taking so long to reply, I never got notified.
This project is 50% done so it's not really possible to use it in its current state. You're more than welcome to fork your own version of it and build it out if you want.

As for documentation, I spoke to Marrs (I think he's the lead dev at rf2) and he sent over an example app where you drag a .jar plugin in to your rf2 install. I then had to dig in to the example angular app that was sent with it and see what endpoints were being used.

If you drop in to the rf2 discord, they should be able to help :)
